#!/bin/bash

set +x

function try_install_salt {
  read -p "I can try to install salt for you, sound good? (Y/n) " choice

  case "$choice" in
    y|Y ) ;;
    *) exit 1 ;;
  esac

  wget -O - https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
  echo "deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest xenial main" > /etc/apt/sources.list.d/saltstack.list
  sudo apt-get update
  sudo apt-get install salt-common
  exit
}

function main {
  which salt-call 2>/dev/null
  exit_code=$?
  if [ ${exit_code} -ne 0 ]; then
    echo "To run this you need to install salt minion."
    try_install_salt
  fi

  local cmd=$1
  if [ "$cmd" == "noop" ]; then
    echo "Running noop..."
    sudo salt-call --local --file-root=root --pillar-root=pillar  state.highstate test=True
  elif [ "$cmd" == "apply" ]; then
    echo "Running apply..."
    sudo salt-call --local --file-root=root --pillar-root=pillar  state.highstate
  elif [ "$cmd" == "setup" ]; then
    echo "Running setup..."
    try_install_salt
  else
    echo "Commands: [noop|apply]"
  fi
}

main $@
